//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CINECLUPModel", "FK_SEANS_FILM", "FILM", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TicketBooking.FILM), "SEANS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TicketBooking.SEAN), true)]
[assembly: EdmRelationshipAttribute("CINECLUPModel", "FK_KOLTUK_SALON", "SALON", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TicketBooking.SALON), "KOLTUK", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TicketBooking.KOLTUK), true)]
[assembly: EdmRelationshipAttribute("CINECLUPModel", "FK_REZERVASYON_KOLTUK", "KOLTUK", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TicketBooking.KOLTUK), "REZERVASYON", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TicketBooking.REZERVASYON), true)]
[assembly: EdmRelationshipAttribute("CINECLUPModel", "FK_REZERVASYON_KULLANICI", "KULLANICI", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TicketBooking.KULLANICI), "REZERVASYON", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TicketBooking.REZERVASYON), true)]
[assembly: EdmRelationshipAttribute("CINECLUPModel", "FK_REZERVASYON_SEANS", "SEANS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TicketBooking.SEAN), "REZERVASYON", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TicketBooking.REZERVASYON), true)]

#endregion

namespace TicketBooking
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CINECLUPEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CINECLUPEntities object using the connection string found in the 'CINECLUPEntities' section of the application configuration file.
        /// </summary>
        public CINECLUPEntities() : base("name=CINECLUPEntities", "CINECLUPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CINECLUPEntities object.
        /// </summary>
        public CINECLUPEntities(string connectionString) : base(connectionString, "CINECLUPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CINECLUPEntities object.
        /// </summary>
        public CINECLUPEntities(EntityConnection connection) : base(connection, "CINECLUPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FILM> FILMs
        {
            get
            {
                if ((_FILMs == null))
                {
                    _FILMs = base.CreateObjectSet<FILM>("FILMs");
                }
                return _FILMs;
            }
        }
        private ObjectSet<FILM> _FILMs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KOLTUK> KOLTUKs
        {
            get
            {
                if ((_KOLTUKs == null))
                {
                    _KOLTUKs = base.CreateObjectSet<KOLTUK>("KOLTUKs");
                }
                return _KOLTUKs;
            }
        }
        private ObjectSet<KOLTUK> _KOLTUKs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KULLANICI> KULLANICIs
        {
            get
            {
                if ((_KULLANICIs == null))
                {
                    _KULLANICIs = base.CreateObjectSet<KULLANICI>("KULLANICIs");
                }
                return _KULLANICIs;
            }
        }
        private ObjectSet<KULLANICI> _KULLANICIs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<REZERVASYON> REZERVASYONs
        {
            get
            {
                if ((_REZERVASYONs == null))
                {
                    _REZERVASYONs = base.CreateObjectSet<REZERVASYON>("REZERVASYONs");
                }
                return _REZERVASYONs;
            }
        }
        private ObjectSet<REZERVASYON> _REZERVASYONs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SALON> SALONs
        {
            get
            {
                if ((_SALONs == null))
                {
                    _SALONs = base.CreateObjectSet<SALON>("SALONs");
                }
                return _SALONs;
            }
        }
        private ObjectSet<SALON> _SALONs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SEAN> SEANS
        {
            get
            {
                if ((_SEANS == null))
                {
                    _SEANS = base.CreateObjectSet<SEAN>("SEANS");
                }
                return _SEANS;
            }
        }
        private ObjectSet<SEAN> _SEANS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<YORUM> YORUMs
        {
            get
            {
                if ((_YORUMs == null))
                {
                    _YORUMs = base.CreateObjectSet<YORUM>("YORUMs");
                }
                return _YORUMs;
            }
        }
        private ObjectSet<YORUM> _YORUMs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FILMs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFILMs(FILM fILM)
        {
            base.AddObject("FILMs", fILM);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KOLTUKs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKOLTUKs(KOLTUK kOLTUK)
        {
            base.AddObject("KOLTUKs", kOLTUK);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KULLANICIs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKULLANICIs(KULLANICI kULLANICI)
        {
            base.AddObject("KULLANICIs", kULLANICI);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the REZERVASYONs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToREZERVASYONs(REZERVASYON rEZERVASYON)
        {
            base.AddObject("REZERVASYONs", rEZERVASYON);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SALONs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSALONs(SALON sALON)
        {
            base.AddObject("SALONs", sALON);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SEANS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSEANS(SEAN sEAN)
        {
            base.AddObject("SEANS", sEAN);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the YORUMs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToYORUMs(YORUM yORUM)
        {
            base.AddObject("YORUMs", yORUM);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<KULLANICI> TumKullanicilariCek()
        {
            return base.ExecuteFunction<KULLANICI>("TumKullanicilariCek");
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        public ObjectResult<KULLANICI> TumKullanicilariCek(MergeOption mergeOption)
        {
            return base.ExecuteFunction<KULLANICI>("TumKullanicilariCek", mergeOption);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mail">No Metadata Documentation available.</param>
        /// <param name="sifre">No Metadata Documentation available.</param>
        public ObjectResult<KULLANICI> KullaniciSorgula(global::System.String mail, global::System.String sifre)
        {
            ObjectParameter mailParameter;
            if (mail != null)
            {
                mailParameter = new ObjectParameter("mail", mail);
            }
            else
            {
                mailParameter = new ObjectParameter("mail", typeof(global::System.String));
            }
    
            ObjectParameter sifreParameter;
            if (sifre != null)
            {
                sifreParameter = new ObjectParameter("sifre", sifre);
            }
            else
            {
                sifreParameter = new ObjectParameter("sifre", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<KULLANICI>("KullaniciSorgula", mailParameter, sifreParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="mail">No Metadata Documentation available.</param>
        /// <param name="sifre">No Metadata Documentation available.</param>
        public ObjectResult<KULLANICI> KullaniciSorgula(global::System.String mail, global::System.String sifre, MergeOption mergeOption)
        {
            ObjectParameter mailParameter;
            if (mail != null)
            {
                mailParameter = new ObjectParameter("mail", mail);
            }
            else
            {
                mailParameter = new ObjectParameter("mail", typeof(global::System.String));
            }
    
            ObjectParameter sifreParameter;
            if (sifre != null)
            {
                sifreParameter = new ObjectParameter("sifre", sifre);
            }
            else
            {
                sifreParameter = new ObjectParameter("sifre", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<KULLANICI>("KullaniciSorgula", mergeOption, mailParameter, sifreParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="k_tipi">No Metadata Documentation available.</param>
        /// <param name="e_posta">No Metadata Documentation available.</param>
        /// <param name="sifre">No Metadata Documentation available.</param>
        /// <param name="k_adi">No Metadata Documentation available.</param>
        /// <param name="k_soyadi">No Metadata Documentation available.</param>
        public int KullaniciEkle(Nullable<global::System.Boolean> k_tipi, global::System.String e_posta, global::System.String sifre, global::System.String k_adi, global::System.String k_soyadi)
        {
            ObjectParameter k_tipiParameter;
            if (k_tipi.HasValue)
            {
                k_tipiParameter = new ObjectParameter("K_tipi", k_tipi);
            }
            else
            {
                k_tipiParameter = new ObjectParameter("K_tipi", typeof(global::System.Boolean));
            }
    
            ObjectParameter e_postaParameter;
            if (e_posta != null)
            {
                e_postaParameter = new ObjectParameter("E_posta", e_posta);
            }
            else
            {
                e_postaParameter = new ObjectParameter("E_posta", typeof(global::System.String));
            }
    
            ObjectParameter sifreParameter;
            if (sifre != null)
            {
                sifreParameter = new ObjectParameter("Sifre", sifre);
            }
            else
            {
                sifreParameter = new ObjectParameter("Sifre", typeof(global::System.String));
            }
    
            ObjectParameter k_adiParameter;
            if (k_adi != null)
            {
                k_adiParameter = new ObjectParameter("K_adi", k_adi);
            }
            else
            {
                k_adiParameter = new ObjectParameter("K_adi", typeof(global::System.String));
            }
    
            ObjectParameter k_soyadiParameter;
            if (k_soyadi != null)
            {
                k_soyadiParameter = new ObjectParameter("K_soyadi", k_soyadi);
            }
            else
            {
                k_soyadiParameter = new ObjectParameter("K_soyadi", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("KullaniciEkle", k_tipiParameter, e_postaParameter, sifreParameter, k_adiParameter, k_soyadiParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="k_ID">No Metadata Documentation available.</param>
        public int KullaniciSil(Nullable<global::System.Int32> k_ID)
        {
            ObjectParameter k_IDParameter;
            if (k_ID.HasValue)
            {
                k_IDParameter = new ObjectParameter("K_ID", k_ID);
            }
            else
            {
                k_IDParameter = new ObjectParameter("K_ID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("KullaniciSil", k_IDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="k_ID">No Metadata Documentation available.</param>
        /// <param name="tip">No Metadata Documentation available.</param>
        /// <param name="mail">No Metadata Documentation available.</param>
        /// <param name="sifre">No Metadata Documentation available.</param>
        public int KullaniciGuncelle(Nullable<global::System.Int32> k_ID, Nullable<global::System.Boolean> tip, global::System.String mail, global::System.String sifre)
        {
            ObjectParameter k_IDParameter;
            if (k_ID.HasValue)
            {
                k_IDParameter = new ObjectParameter("K_ID", k_ID);
            }
            else
            {
                k_IDParameter = new ObjectParameter("K_ID", typeof(global::System.Int32));
            }
    
            ObjectParameter tipParameter;
            if (tip.HasValue)
            {
                tipParameter = new ObjectParameter("tip", tip);
            }
            else
            {
                tipParameter = new ObjectParameter("tip", typeof(global::System.Boolean));
            }
    
            ObjectParameter mailParameter;
            if (mail != null)
            {
                mailParameter = new ObjectParameter("mail", mail);
            }
            else
            {
                mailParameter = new ObjectParameter("mail", typeof(global::System.String));
            }
    
            ObjectParameter sifreParameter;
            if (sifre != null)
            {
                sifreParameter = new ObjectParameter("sifre", sifre);
            }
            else
            {
                sifreParameter = new ObjectParameter("sifre", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("KullaniciGuncelle", k_IDParameter, tipParameter, mailParameter, sifreParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CINECLUPModel", Name="FILM")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FILM : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FILM object.
        /// </summary>
        /// <param name="filmID">Initial value of the FilmID property.</param>
        /// <param name="film_Adı">Initial value of the Film_Adı property.</param>
        /// <param name="yapım_Yılı">Initial value of the Yapım_Yılı property.</param>
        /// <param name="a_D">Initial value of the A_D property.</param>
        /// <param name="d3">Initial value of the D3 property.</param>
        /// <param name="ekleme_Tarihi">Initial value of the Ekleme_Tarihi property.</param>
        /// <param name="bitis_Tarihi">Initial value of the Bitis_Tarihi property.</param>
        /// <param name="afis_URL">Initial value of the Afis_URL property.</param>
        /// <param name="geldiMi">Initial value of the GeldiMi property.</param>
        public static FILM CreateFILM(global::System.Int32 filmID, global::System.String film_Adı, global::System.Int32 yapım_Yılı, global::System.Boolean a_D, global::System.Boolean d3, global::System.DateTime ekleme_Tarihi, global::System.DateTime bitis_Tarihi, global::System.String afis_URL, global::System.Boolean geldiMi)
        {
            FILM fILM = new FILM();
            fILM.FilmID = filmID;
            fILM.Film_Adı = film_Adı;
            fILM.Yapım_Yılı = yapım_Yılı;
            fILM.A_D = a_D;
            fILM.D3 = d3;
            fILM.Ekleme_Tarihi = ekleme_Tarihi;
            fILM.Bitis_Tarihi = bitis_Tarihi;
            fILM.Afis_URL = afis_URL;
            fILM.GeldiMi = geldiMi;
            return fILM;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FilmID
        {
            get
            {
                return _FilmID;
            }
            set
            {
                if (_FilmID != value)
                {
                    OnFilmIDChanging(value);
                    ReportPropertyChanging("FilmID");
                    _FilmID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FilmID");
                    OnFilmIDChanged();
                }
            }
        }
        private global::System.Int32 _FilmID;
        partial void OnFilmIDChanging(global::System.Int32 value);
        partial void OnFilmIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Film_Adı
        {
            get
            {
                return _Film_Adı;
            }
            set
            {
                OnFilm_AdıChanging(value);
                ReportPropertyChanging("Film_Adı");
                _Film_Adı = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Film_Adı");
                OnFilm_AdıChanged();
            }
        }
        private global::System.String _Film_Adı;
        partial void OnFilm_AdıChanging(global::System.String value);
        partial void OnFilm_AdıChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Yapım_Yılı
        {
            get
            {
                return _Yapım_Yılı;
            }
            set
            {
                OnYapım_YılıChanging(value);
                ReportPropertyChanging("Yapım_Yılı");
                _Yapım_Yılı = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Yapım_Yılı");
                OnYapım_YılıChanged();
            }
        }
        private global::System.Int32 _Yapım_Yılı;
        partial void OnYapım_YılıChanging(global::System.Int32 value);
        partial void OnYapım_YılıChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean A_D
        {
            get
            {
                return _A_D;
            }
            set
            {
                OnA_DChanging(value);
                ReportPropertyChanging("A_D");
                _A_D = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("A_D");
                OnA_DChanged();
            }
        }
        private global::System.Boolean _A_D;
        partial void OnA_DChanging(global::System.Boolean value);
        partial void OnA_DChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean D3
        {
            get
            {
                return _D3;
            }
            set
            {
                OnD3Changing(value);
                ReportPropertyChanging("D3");
                _D3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("D3");
                OnD3Changed();
            }
        }
        private global::System.Boolean _D3;
        partial void OnD3Changing(global::System.Boolean value);
        partial void OnD3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Ekleme_Tarihi
        {
            get
            {
                return _Ekleme_Tarihi;
            }
            set
            {
                OnEkleme_TarihiChanging(value);
                ReportPropertyChanging("Ekleme_Tarihi");
                _Ekleme_Tarihi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ekleme_Tarihi");
                OnEkleme_TarihiChanged();
            }
        }
        private global::System.DateTime _Ekleme_Tarihi;
        partial void OnEkleme_TarihiChanging(global::System.DateTime value);
        partial void OnEkleme_TarihiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Bitis_Tarihi
        {
            get
            {
                return _Bitis_Tarihi;
            }
            set
            {
                OnBitis_TarihiChanging(value);
                ReportPropertyChanging("Bitis_Tarihi");
                _Bitis_Tarihi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bitis_Tarihi");
                OnBitis_TarihiChanged();
            }
        }
        private global::System.DateTime _Bitis_Tarihi;
        partial void OnBitis_TarihiChanging(global::System.DateTime value);
        partial void OnBitis_TarihiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Afis_URL
        {
            get
            {
                return _Afis_URL;
            }
            set
            {
                OnAfis_URLChanging(value);
                ReportPropertyChanging("Afis_URL");
                _Afis_URL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Afis_URL");
                OnAfis_URLChanged();
            }
        }
        private global::System.String _Afis_URL;
        partial void OnAfis_URLChanging(global::System.String value);
        partial void OnAfis_URLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean GeldiMi
        {
            get
            {
                return _GeldiMi;
            }
            set
            {
                OnGeldiMiChanging(value);
                ReportPropertyChanging("GeldiMi");
                _GeldiMi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GeldiMi");
                OnGeldiMiChanged();
            }
        }
        private global::System.Boolean _GeldiMi;
        partial void OnGeldiMiChanging(global::System.Boolean value);
        partial void OnGeldiMiChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CINECLUPModel", "FK_SEANS_FILM", "SEANS")]
        public EntityCollection<SEAN> SEANS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SEAN>("CINECLUPModel.FK_SEANS_FILM", "SEANS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SEAN>("CINECLUPModel.FK_SEANS_FILM", "SEANS", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CINECLUPModel", Name="KOLTUK")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KOLTUK : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KOLTUK object.
        /// </summary>
        /// <param name="koltuk_ID">Initial value of the Koltuk_ID property.</param>
        /// <param name="salon_ID">Initial value of the Salon_ID property.</param>
        /// <param name="satır_No">Initial value of the Satır_No property.</param>
        /// <param name="sutun_No">Initial value of the Sutun_No property.</param>
        /// <param name="loveSeat">Initial value of the LoveSeat property.</param>
        public static KOLTUK CreateKOLTUK(global::System.Int32 koltuk_ID, global::System.Int32 salon_ID, global::System.Int32 satır_No, global::System.Int32 sutun_No, global::System.Boolean loveSeat)
        {
            KOLTUK kOLTUK = new KOLTUK();
            kOLTUK.Koltuk_ID = koltuk_ID;
            kOLTUK.Salon_ID = salon_ID;
            kOLTUK.Satır_No = satır_No;
            kOLTUK.Sutun_No = sutun_No;
            kOLTUK.LoveSeat = loveSeat;
            return kOLTUK;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Koltuk_ID
        {
            get
            {
                return _Koltuk_ID;
            }
            set
            {
                if (_Koltuk_ID != value)
                {
                    OnKoltuk_IDChanging(value);
                    ReportPropertyChanging("Koltuk_ID");
                    _Koltuk_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Koltuk_ID");
                    OnKoltuk_IDChanged();
                }
            }
        }
        private global::System.Int32 _Koltuk_ID;
        partial void OnKoltuk_IDChanging(global::System.Int32 value);
        partial void OnKoltuk_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Salon_ID
        {
            get
            {
                return _Salon_ID;
            }
            set
            {
                OnSalon_IDChanging(value);
                ReportPropertyChanging("Salon_ID");
                _Salon_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Salon_ID");
                OnSalon_IDChanged();
            }
        }
        private global::System.Int32 _Salon_ID;
        partial void OnSalon_IDChanging(global::System.Int32 value);
        partial void OnSalon_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Satır_No
        {
            get
            {
                return _Satır_No;
            }
            set
            {
                OnSatır_NoChanging(value);
                ReportPropertyChanging("Satır_No");
                _Satır_No = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Satır_No");
                OnSatır_NoChanged();
            }
        }
        private global::System.Int32 _Satır_No;
        partial void OnSatır_NoChanging(global::System.Int32 value);
        partial void OnSatır_NoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Sutun_No
        {
            get
            {
                return _Sutun_No;
            }
            set
            {
                OnSutun_NoChanging(value);
                ReportPropertyChanging("Sutun_No");
                _Sutun_No = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sutun_No");
                OnSutun_NoChanged();
            }
        }
        private global::System.Int32 _Sutun_No;
        partial void OnSutun_NoChanging(global::System.Int32 value);
        partial void OnSutun_NoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean LoveSeat
        {
            get
            {
                return _LoveSeat;
            }
            set
            {
                OnLoveSeatChanging(value);
                ReportPropertyChanging("LoveSeat");
                _LoveSeat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoveSeat");
                OnLoveSeatChanged();
            }
        }
        private global::System.Boolean _LoveSeat;
        partial void OnLoveSeatChanging(global::System.Boolean value);
        partial void OnLoveSeatChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CINECLUPModel", "FK_KOLTUK_SALON", "SALON")]
        public SALON SALON
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SALON>("CINECLUPModel.FK_KOLTUK_SALON", "SALON").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SALON>("CINECLUPModel.FK_KOLTUK_SALON", "SALON").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SALON> SALONReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SALON>("CINECLUPModel.FK_KOLTUK_SALON", "SALON");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SALON>("CINECLUPModel.FK_KOLTUK_SALON", "SALON", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CINECLUPModel", "FK_REZERVASYON_KOLTUK", "REZERVASYON")]
        public EntityCollection<REZERVASYON> REZERVASYONs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<REZERVASYON>("CINECLUPModel.FK_REZERVASYON_KOLTUK", "REZERVASYON");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<REZERVASYON>("CINECLUPModel.FK_REZERVASYON_KOLTUK", "REZERVASYON", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CINECLUPModel", Name="KULLANICI")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KULLANICI : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KULLANICI object.
        /// </summary>
        /// <param name="kullanici_ID">Initial value of the Kullanici_ID property.</param>
        /// <param name="kullanici_Tipi">Initial value of the Kullanici_Tipi property.</param>
        /// <param name="eposta">Initial value of the Eposta property.</param>
        /// <param name="sifre">Initial value of the Sifre property.</param>
        /// <param name="kayit_Tarihi">Initial value of the Kayit_Tarihi property.</param>
        /// <param name="ad">Initial value of the Ad property.</param>
        /// <param name="soyad">Initial value of the Soyad property.</param>
        /// <param name="puan">Initial value of the Puan property.</param>
        public static KULLANICI CreateKULLANICI(global::System.Int32 kullanici_ID, global::System.Boolean kullanici_Tipi, global::System.String eposta, global::System.String sifre, global::System.DateTime kayit_Tarihi, global::System.String ad, global::System.String soyad, global::System.Int32 puan)
        {
            KULLANICI kULLANICI = new KULLANICI();
            kULLANICI.Kullanici_ID = kullanici_ID;
            kULLANICI.Kullanici_Tipi = kullanici_Tipi;
            kULLANICI.Eposta = eposta;
            kULLANICI.Sifre = sifre;
            kULLANICI.Kayit_Tarihi = kayit_Tarihi;
            kULLANICI.Ad = ad;
            kULLANICI.Soyad = soyad;
            kULLANICI.Puan = puan;
            return kULLANICI;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Kullanici_ID
        {
            get
            {
                return _Kullanici_ID;
            }
            set
            {
                if (_Kullanici_ID != value)
                {
                    OnKullanici_IDChanging(value);
                    ReportPropertyChanging("Kullanici_ID");
                    _Kullanici_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Kullanici_ID");
                    OnKullanici_IDChanged();
                }
            }
        }
        private global::System.Int32 _Kullanici_ID;
        partial void OnKullanici_IDChanging(global::System.Int32 value);
        partial void OnKullanici_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Kullanici_Tipi
        {
            get
            {
                return _Kullanici_Tipi;
            }
            set
            {
                OnKullanici_TipiChanging(value);
                ReportPropertyChanging("Kullanici_Tipi");
                _Kullanici_Tipi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Kullanici_Tipi");
                OnKullanici_TipiChanged();
            }
        }
        private global::System.Boolean _Kullanici_Tipi;
        partial void OnKullanici_TipiChanging(global::System.Boolean value);
        partial void OnKullanici_TipiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Eposta
        {
            get
            {
                return _Eposta;
            }
            set
            {
                OnEpostaChanging(value);
                ReportPropertyChanging("Eposta");
                _Eposta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Eposta");
                OnEpostaChanged();
            }
        }
        private global::System.String _Eposta;
        partial void OnEpostaChanging(global::System.String value);
        partial void OnEpostaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sifre
        {
            get
            {
                return _Sifre;
            }
            set
            {
                OnSifreChanging(value);
                ReportPropertyChanging("Sifre");
                _Sifre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sifre");
                OnSifreChanged();
            }
        }
        private global::System.String _Sifre;
        partial void OnSifreChanging(global::System.String value);
        partial void OnSifreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Kayit_Tarihi
        {
            get
            {
                return _Kayit_Tarihi;
            }
            set
            {
                OnKayit_TarihiChanging(value);
                ReportPropertyChanging("Kayit_Tarihi");
                _Kayit_Tarihi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Kayit_Tarihi");
                OnKayit_TarihiChanged();
            }
        }
        private global::System.DateTime _Kayit_Tarihi;
        partial void OnKayit_TarihiChanging(global::System.DateTime value);
        partial void OnKayit_TarihiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ad
        {
            get
            {
                return _Ad;
            }
            set
            {
                OnAdChanging(value);
                ReportPropertyChanging("Ad");
                _Ad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ad");
                OnAdChanged();
            }
        }
        private global::System.String _Ad;
        partial void OnAdChanging(global::System.String value);
        partial void OnAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Soyad
        {
            get
            {
                return _Soyad;
            }
            set
            {
                OnSoyadChanging(value);
                ReportPropertyChanging("Soyad");
                _Soyad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Soyad");
                OnSoyadChanged();
            }
        }
        private global::System.String _Soyad;
        partial void OnSoyadChanging(global::System.String value);
        partial void OnSoyadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Puan
        {
            get
            {
                return _Puan;
            }
            set
            {
                OnPuanChanging(value);
                ReportPropertyChanging("Puan");
                _Puan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Puan");
                OnPuanChanged();
            }
        }
        private global::System.Int32 _Puan;
        partial void OnPuanChanging(global::System.Int32 value);
        partial void OnPuanChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CINECLUPModel", "FK_REZERVASYON_KULLANICI", "REZERVASYON")]
        public EntityCollection<REZERVASYON> REZERVASYONs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<REZERVASYON>("CINECLUPModel.FK_REZERVASYON_KULLANICI", "REZERVASYON");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<REZERVASYON>("CINECLUPModel.FK_REZERVASYON_KULLANICI", "REZERVASYON", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CINECLUPModel", Name="REZERVASYON")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class REZERVASYON : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new REZERVASYON object.
        /// </summary>
        /// <param name="rez_ID">Initial value of the Rez_ID property.</param>
        /// <param name="kullanıcı_ID">Initial value of the Kullanıcı_ID property.</param>
        /// <param name="seans_ID">Initial value of the Seans_ID property.</param>
        /// <param name="koltuk_ID">Initial value of the Koltuk_ID property.</param>
        /// <param name="tarih">Initial value of the Tarih property.</param>
        /// <param name="satildiMi">Initial value of the SatildiMi property.</param>
        public static REZERVASYON CreateREZERVASYON(global::System.Int32 rez_ID, global::System.Int32 kullanıcı_ID, global::System.Int32 seans_ID, global::System.Int32 koltuk_ID, global::System.DateTime tarih, global::System.Boolean satildiMi)
        {
            REZERVASYON rEZERVASYON = new REZERVASYON();
            rEZERVASYON.Rez_ID = rez_ID;
            rEZERVASYON.Kullanıcı_ID = kullanıcı_ID;
            rEZERVASYON.Seans_ID = seans_ID;
            rEZERVASYON.Koltuk_ID = koltuk_ID;
            rEZERVASYON.Tarih = tarih;
            rEZERVASYON.SatildiMi = satildiMi;
            return rEZERVASYON;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Rez_ID
        {
            get
            {
                return _Rez_ID;
            }
            set
            {
                if (_Rez_ID != value)
                {
                    OnRez_IDChanging(value);
                    ReportPropertyChanging("Rez_ID");
                    _Rez_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Rez_ID");
                    OnRez_IDChanged();
                }
            }
        }
        private global::System.Int32 _Rez_ID;
        partial void OnRez_IDChanging(global::System.Int32 value);
        partial void OnRez_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Kullanıcı_ID
        {
            get
            {
                return _Kullanıcı_ID;
            }
            set
            {
                OnKullanıcı_IDChanging(value);
                ReportPropertyChanging("Kullanıcı_ID");
                _Kullanıcı_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Kullanıcı_ID");
                OnKullanıcı_IDChanged();
            }
        }
        private global::System.Int32 _Kullanıcı_ID;
        partial void OnKullanıcı_IDChanging(global::System.Int32 value);
        partial void OnKullanıcı_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Seans_ID
        {
            get
            {
                return _Seans_ID;
            }
            set
            {
                OnSeans_IDChanging(value);
                ReportPropertyChanging("Seans_ID");
                _Seans_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Seans_ID");
                OnSeans_IDChanged();
            }
        }
        private global::System.Int32 _Seans_ID;
        partial void OnSeans_IDChanging(global::System.Int32 value);
        partial void OnSeans_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Koltuk_ID
        {
            get
            {
                return _Koltuk_ID;
            }
            set
            {
                OnKoltuk_IDChanging(value);
                ReportPropertyChanging("Koltuk_ID");
                _Koltuk_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Koltuk_ID");
                OnKoltuk_IDChanged();
            }
        }
        private global::System.Int32 _Koltuk_ID;
        partial void OnKoltuk_IDChanging(global::System.Int32 value);
        partial void OnKoltuk_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Tarih
        {
            get
            {
                return _Tarih;
            }
            set
            {
                OnTarihChanging(value);
                ReportPropertyChanging("Tarih");
                _Tarih = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tarih");
                OnTarihChanged();
            }
        }
        private global::System.DateTime _Tarih;
        partial void OnTarihChanging(global::System.DateTime value);
        partial void OnTarihChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean SatildiMi
        {
            get
            {
                return _SatildiMi;
            }
            set
            {
                OnSatildiMiChanging(value);
                ReportPropertyChanging("SatildiMi");
                _SatildiMi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SatildiMi");
                OnSatildiMiChanged();
            }
        }
        private global::System.Boolean _SatildiMi;
        partial void OnSatildiMiChanging(global::System.Boolean value);
        partial void OnSatildiMiChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CINECLUPModel", "FK_REZERVASYON_KOLTUK", "KOLTUK")]
        public KOLTUK KOLTUK
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KOLTUK>("CINECLUPModel.FK_REZERVASYON_KOLTUK", "KOLTUK").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KOLTUK>("CINECLUPModel.FK_REZERVASYON_KOLTUK", "KOLTUK").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<KOLTUK> KOLTUKReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KOLTUK>("CINECLUPModel.FK_REZERVASYON_KOLTUK", "KOLTUK");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<KOLTUK>("CINECLUPModel.FK_REZERVASYON_KOLTUK", "KOLTUK", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CINECLUPModel", "FK_REZERVASYON_KULLANICI", "KULLANICI")]
        public KULLANICI KULLANICI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KULLANICI>("CINECLUPModel.FK_REZERVASYON_KULLANICI", "KULLANICI").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KULLANICI>("CINECLUPModel.FK_REZERVASYON_KULLANICI", "KULLANICI").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<KULLANICI> KULLANICIReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KULLANICI>("CINECLUPModel.FK_REZERVASYON_KULLANICI", "KULLANICI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<KULLANICI>("CINECLUPModel.FK_REZERVASYON_KULLANICI", "KULLANICI", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CINECLUPModel", "FK_REZERVASYON_SEANS", "SEANS")]
        public SEAN SEAN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SEAN>("CINECLUPModel.FK_REZERVASYON_SEANS", "SEANS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SEAN>("CINECLUPModel.FK_REZERVASYON_SEANS", "SEANS").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SEAN> SEANReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SEAN>("CINECLUPModel.FK_REZERVASYON_SEANS", "SEANS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SEAN>("CINECLUPModel.FK_REZERVASYON_SEANS", "SEANS", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CINECLUPModel", Name="SALON")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SALON : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SALON object.
        /// </summary>
        /// <param name="salon_ID">Initial value of the Salon_ID property.</param>
        /// <param name="salon_Adı">Initial value of the Salon_Adı property.</param>
        /// <param name="kapasite">Initial value of the Kapasite property.</param>
        /// <param name="eklenme_Tarihi">Initial value of the Eklenme_Tarihi property.</param>
        public static SALON CreateSALON(global::System.Int32 salon_ID, global::System.String salon_Adı, global::System.Int32 kapasite, global::System.DateTime eklenme_Tarihi)
        {
            SALON sALON = new SALON();
            sALON.Salon_ID = salon_ID;
            sALON.Salon_Adı = salon_Adı;
            sALON.Kapasite = kapasite;
            sALON.Eklenme_Tarihi = eklenme_Tarihi;
            return sALON;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Salon_ID
        {
            get
            {
                return _Salon_ID;
            }
            set
            {
                if (_Salon_ID != value)
                {
                    OnSalon_IDChanging(value);
                    ReportPropertyChanging("Salon_ID");
                    _Salon_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Salon_ID");
                    OnSalon_IDChanged();
                }
            }
        }
        private global::System.Int32 _Salon_ID;
        partial void OnSalon_IDChanging(global::System.Int32 value);
        partial void OnSalon_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Salon_Adı
        {
            get
            {
                return _Salon_Adı;
            }
            set
            {
                OnSalon_AdıChanging(value);
                ReportPropertyChanging("Salon_Adı");
                _Salon_Adı = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Salon_Adı");
                OnSalon_AdıChanged();
            }
        }
        private global::System.String _Salon_Adı;
        partial void OnSalon_AdıChanging(global::System.String value);
        partial void OnSalon_AdıChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Kapasite
        {
            get
            {
                return _Kapasite;
            }
            set
            {
                OnKapasiteChanging(value);
                ReportPropertyChanging("Kapasite");
                _Kapasite = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Kapasite");
                OnKapasiteChanged();
            }
        }
        private global::System.Int32 _Kapasite;
        partial void OnKapasiteChanging(global::System.Int32 value);
        partial void OnKapasiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Eklenme_Tarihi
        {
            get
            {
                return _Eklenme_Tarihi;
            }
            set
            {
                OnEklenme_TarihiChanging(value);
                ReportPropertyChanging("Eklenme_Tarihi");
                _Eklenme_Tarihi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Eklenme_Tarihi");
                OnEklenme_TarihiChanged();
            }
        }
        private global::System.DateTime _Eklenme_Tarihi;
        partial void OnEklenme_TarihiChanging(global::System.DateTime value);
        partial void OnEklenme_TarihiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Açıklama
        {
            get
            {
                return _Açıklama;
            }
            set
            {
                OnAçıklamaChanging(value);
                ReportPropertyChanging("Açıklama");
                _Açıklama = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Açıklama");
                OnAçıklamaChanged();
            }
        }
        private global::System.String _Açıklama;
        partial void OnAçıklamaChanging(global::System.String value);
        partial void OnAçıklamaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CINECLUPModel", "FK_KOLTUK_SALON", "KOLTUK")]
        public EntityCollection<KOLTUK> KOLTUKs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<KOLTUK>("CINECLUPModel.FK_KOLTUK_SALON", "KOLTUK");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<KOLTUK>("CINECLUPModel.FK_KOLTUK_SALON", "KOLTUK", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CINECLUPModel", Name="SEAN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SEAN : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SEAN object.
        /// </summary>
        /// <param name="seans_ID">Initial value of the Seans_ID property.</param>
        /// <param name="film_ID">Initial value of the Film_ID property.</param>
        /// <param name="salon_ID">Initial value of the Salon_ID property.</param>
        /// <param name="saat">Initial value of the Saat property.</param>
        public static SEAN CreateSEAN(global::System.Int32 seans_ID, global::System.Int32 film_ID, global::System.Int32 salon_ID, global::System.TimeSpan saat)
        {
            SEAN sEAN = new SEAN();
            sEAN.Seans_ID = seans_ID;
            sEAN.Film_ID = film_ID;
            sEAN.Salon_ID = salon_ID;
            sEAN.Saat = saat;
            return sEAN;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Seans_ID
        {
            get
            {
                return _Seans_ID;
            }
            set
            {
                if (_Seans_ID != value)
                {
                    OnSeans_IDChanging(value);
                    ReportPropertyChanging("Seans_ID");
                    _Seans_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Seans_ID");
                    OnSeans_IDChanged();
                }
            }
        }
        private global::System.Int32 _Seans_ID;
        partial void OnSeans_IDChanging(global::System.Int32 value);
        partial void OnSeans_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Film_ID
        {
            get
            {
                return _Film_ID;
            }
            set
            {
                OnFilm_IDChanging(value);
                ReportPropertyChanging("Film_ID");
                _Film_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Film_ID");
                OnFilm_IDChanged();
            }
        }
        private global::System.Int32 _Film_ID;
        partial void OnFilm_IDChanging(global::System.Int32 value);
        partial void OnFilm_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Salon_ID
        {
            get
            {
                return _Salon_ID;
            }
            set
            {
                OnSalon_IDChanging(value);
                ReportPropertyChanging("Salon_ID");
                _Salon_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Salon_ID");
                OnSalon_IDChanged();
            }
        }
        private global::System.Int32 _Salon_ID;
        partial void OnSalon_IDChanging(global::System.Int32 value);
        partial void OnSalon_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan Saat
        {
            get
            {
                return _Saat;
            }
            set
            {
                OnSaatChanging(value);
                ReportPropertyChanging("Saat");
                _Saat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Saat");
                OnSaatChanged();
            }
        }
        private global::System.TimeSpan _Saat;
        partial void OnSaatChanging(global::System.TimeSpan value);
        partial void OnSaatChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CINECLUPModel", "FK_SEANS_FILM", "FILM")]
        public FILM FILM
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FILM>("CINECLUPModel.FK_SEANS_FILM", "FILM").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FILM>("CINECLUPModel.FK_SEANS_FILM", "FILM").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FILM> FILMReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FILM>("CINECLUPModel.FK_SEANS_FILM", "FILM");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FILM>("CINECLUPModel.FK_SEANS_FILM", "FILM", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CINECLUPModel", "FK_REZERVASYON_SEANS", "REZERVASYON")]
        public EntityCollection<REZERVASYON> REZERVASYONs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<REZERVASYON>("CINECLUPModel.FK_REZERVASYON_SEANS", "REZERVASYON");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<REZERVASYON>("CINECLUPModel.FK_REZERVASYON_SEANS", "REZERVASYON", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CINECLUPModel", Name="YORUM")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class YORUM : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new YORUM object.
        /// </summary>
        /// <param name="yorum_ID">Initial value of the Yorum_ID property.</param>
        /// <param name="kullanici_ID">Initial value of the Kullanici_ID property.</param>
        /// <param name="film_ID">Initial value of the Film_ID property.</param>
        /// <param name="yorum1">Initial value of the Yorum1 property.</param>
        /// <param name="tarih">Initial value of the Tarih property.</param>
        /// <param name="saat">Initial value of the Saat property.</param>
        public static YORUM CreateYORUM(global::System.Int32 yorum_ID, global::System.Int32 kullanici_ID, global::System.Int32 film_ID, global::System.String yorum1, global::System.DateTime tarih, global::System.TimeSpan saat)
        {
            YORUM yORUM = new YORUM();
            yORUM.Yorum_ID = yorum_ID;
            yORUM.Kullanici_ID = kullanici_ID;
            yORUM.Film_ID = film_ID;
            yORUM.Yorum1 = yorum1;
            yORUM.Tarih = tarih;
            yORUM.Saat = saat;
            return yORUM;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Yorum_ID
        {
            get
            {
                return _Yorum_ID;
            }
            set
            {
                if (_Yorum_ID != value)
                {
                    OnYorum_IDChanging(value);
                    ReportPropertyChanging("Yorum_ID");
                    _Yorum_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Yorum_ID");
                    OnYorum_IDChanged();
                }
            }
        }
        private global::System.Int32 _Yorum_ID;
        partial void OnYorum_IDChanging(global::System.Int32 value);
        partial void OnYorum_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Kullanici_ID
        {
            get
            {
                return _Kullanici_ID;
            }
            set
            {
                OnKullanici_IDChanging(value);
                ReportPropertyChanging("Kullanici_ID");
                _Kullanici_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Kullanici_ID");
                OnKullanici_IDChanged();
            }
        }
        private global::System.Int32 _Kullanici_ID;
        partial void OnKullanici_IDChanging(global::System.Int32 value);
        partial void OnKullanici_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Film_ID
        {
            get
            {
                return _Film_ID;
            }
            set
            {
                OnFilm_IDChanging(value);
                ReportPropertyChanging("Film_ID");
                _Film_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Film_ID");
                OnFilm_IDChanged();
            }
        }
        private global::System.Int32 _Film_ID;
        partial void OnFilm_IDChanging(global::System.Int32 value);
        partial void OnFilm_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Yorum1
        {
            get
            {
                return _Yorum1;
            }
            set
            {
                OnYorum1Changing(value);
                ReportPropertyChanging("Yorum1");
                _Yorum1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Yorum1");
                OnYorum1Changed();
            }
        }
        private global::System.String _Yorum1;
        partial void OnYorum1Changing(global::System.String value);
        partial void OnYorum1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Tarih
        {
            get
            {
                return _Tarih;
            }
            set
            {
                OnTarihChanging(value);
                ReportPropertyChanging("Tarih");
                _Tarih = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tarih");
                OnTarihChanged();
            }
        }
        private global::System.DateTime _Tarih;
        partial void OnTarihChanging(global::System.DateTime value);
        partial void OnTarihChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan Saat
        {
            get
            {
                return _Saat;
            }
            set
            {
                OnSaatChanging(value);
                ReportPropertyChanging("Saat");
                _Saat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Saat");
                OnSaatChanged();
            }
        }
        private global::System.TimeSpan _Saat;
        partial void OnSaatChanging(global::System.TimeSpan value);
        partial void OnSaatChanged();

        #endregion
    
    }

    #endregion
    
}
